#!/bin/bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Get the hostname of the server
hostname=$(hostname)

# Configure Nginx to add the custom header
sudo bash -c 'cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    	add_header X-Served-By $hostname;
    }
}
EOL'

# Enable the default site
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx to apply changes
sudo service nginx restart
