#!/usr/bin/env bash
# Bash script that displays To inifity and beyond indefinitely. With a sleep 2 in between each iteration

for (( i=1; i>0; i++ ))
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM

done
