#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and: displays 4 and then bad luck from China for the 4th loop iteration displays 9 and then bad luck from Japan for the 9th loop iteration displays 17 and then bad luck from Italy for the 17th loop iteration

h=0

while [ $h -le 12 ]
do
     echo "Hour: $h"
     m=1
     while [ $m -le 59 ]
     do
	 echo "$m"
	 ((m++))
     done

     ((h++))
done
