#!/usr/bin/env bash
# Configures a UFW Firewall to block all incoming and allow all outcoming data
# Except port 80, 22, and 443

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
