#!/usr/bin/env bash
# Script should run the whoami command under the user passed

chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chmod 700 /etc/nginx/nginx.conf
pkill -f apache2
sudo -u nginx service nginx start
